name: Github action Example

 on:
  pull_request:
  push:
   branches:
      -master
      -develop
  
  jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: npm install
      - name: Test         
        run: npm test
